---
- hosts: dev
  become: true
  tasks:
    - name: Install Python
      apt:
        name: python3
        state: present
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    - name: Install Python pip
      apt:
        name: python-pip
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    - name: Install docker
      pip:
        name: docker
        state: present
        # enabled: yes
    - name: Start Docker
      service:
        name: docker
        state: started
    - name: Start Docker Container
      docker_container:
        name: php-demo-app
        image: "mohanraj612/php-app:php-demo-app"
        state: started
        published_ports:
          - 0.0.0.0:8888:80
          - 0.0.0.0:3307:3306