---
- hosts: dev
  become: true
  tasks:
    - name: Install Python pip
      apt:
        name: python3-pip
        state: present
    - name: Install Docker
      apt:
        name: docker
        state: present
    - name: Install docker-py
      pip:
        name: docker-py
        state: started
        enabled: yes
    - name: Start Docker
      service:
        name: docker
        state: started
    - name: Start Docker Container
      docker_container:
        name: php-demo-app
        image: php-demo-app
        state: started
        published_ports:
          - 0.0.0.0:8888:80
          - 0.0.0.0:3307:3306